#
#  ╔════════════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ██████╗░░█████╗░░█████╗░░██████╗████████╗███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗ ║
#  ║ ██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝ ║
#  ║ ██████╦╝██║░░██║██║░░██║╚█████╗░░░░██║░░░█████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░ ║
#  ║ ██╔══██╗██║░░██║██║░░██║░╚═══██╗░░░██║░░░██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░ ║
#  ║ ██████╦╝╚█████╔╝╚█████╔╝██████╔╝░░░██║░░░███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░ ║
#  ║ ╚═════╝░░╚════╝░░╚════╝░╚═════╝░░░░╚═╝░░░╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════════════╝
#
# Watch the full resource in GitHub
# https://github.com/ItsWagPvP/BoostEconomy.git
#
# Discord: https://discord.gg/x4mdfwWs8P
# www.boostdevteam.eu

# Do not change the version
Version: 1.4.1

# You can find a list in the BoostEconomy/Messages folder and you can change that!
Language: en_US

# Settings
Config:

  # The format for the %boosteconomy_x_formatted%
  # 1000 = 1k
  # 100000000 = 1M
  # 100000000000 = 1B
  # 100000000000000000 = 1T
  # 100000000000000000000 = 1Q
  Format:
      k: "k"
      M: "M"
      B: "B"
      T: "T"
      Q: "Q"

  # Will write all the action of the plugin in the BoostEconomy/log.txt file
  Logs: true

  # Will hook with PlaceholderAPI and loads the placeholders
  Placeholders: true

  # Control if the plugin is outdated (Only works in 1.12+)
  CheckForUpdates:

    # The updater will send to the console if the plugin is outdated in the startup
    Console: true

    # The updater will send a message to the player that have the "boosteconomy.checkforupdates" permission
    Player: true

  # When a player join he will have this money by default
  StartMoney: 0.00

  # Send to the console the message of saving data
  ConsoleSaveMessage: true

  # Do you want to use sounds of success or error?
  UseSounds: true
  Sounds:

    # Played when a player do an action and it works fine
    Success: "ENTITY_PLAYER_LEVELUP"

    # Played when a player do an action and it don't works fine
    Error: "ENTITY_VILLAGER_NO"

GUI:

  # GUI Of /money
  Money:
    UseGUI: false
    Title: "&9&lMoney"

    # /money
    YourHead: "&cYou have %money%$"

    # /money <player>
    OthersHead: "&c%target% has %money%$"

  # GUI Of /baltop
  BalTop:
    UseGUI: false
    Title: "&9&lTop 10 balances"

    # The position in the baltop
    Number: "&b&l%number%°"

    # Description of the item
    Lore: "&f&l%player%: &c%money%"

# Banknotes system
Banknotes:

  # Enable banknotes?
  UseBanknotes: true

  # Which material do you want to use?
  Material: PAPER

  # If your server version is old and you have block ID it's like 100:10
  # The :10 is the data
  Data: 0

  # Name of the item
  Name: "&9Banknotes"

  # Do you want to use limits?
  Enable-Maximum: false
  Maximum-Withdraw-Amount: 100000000
  Enable-Minimum: false
  Minimun-Withdraw-Amount: 0

  # When console give with /banknotes give <name> <money>
  # The lore is "Withdrawn by Console"
  Console-Name: "Console"

  # Description of the item
  Lore:
    - "&7Value: &a%money%"
    - "&7Withdrawn by &a%player%"

  # Right-Click on air or to a block will deposit the banknote
  Allow-Right-Click-To-Deposit-Notes: true

# For more options go in the mobs.yml file
# To customize the message go in the /Messages folder and edit your file!
Entity:

  # Do you want to use the MobReward function?
  Enable: true

  # Send message to the player when he kills an entity?
  Message: false

  # Send ActionBar message?
  ActionBar: true

